#!/bin/bash
set -e
app=tagspaces

# Retrieve arguments
domain=$1
path=$2
is_public=$3
version=$4

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Save app settings
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app path -v "$path"
sudo yunohost app setting $app is_public -v "$is_public"
sudo yunohost app setting $app version -v "$version"

# Create the directory
final_path=/var/www/$app
sudo mkdir -p $final_path

# Install version from source or from YunoHost
if [ "$version" = "YunoHost version" ];
then
	sudo cp -a ../sources/. $final_path
else
	git clone https://github.com/tagspaces/tagspaces
	sudo rm -rf tagspaces/data/chrome tagspaces/data/chromelight tagspaces/data/cordova tagspaces/data/mozilla tagspaces/data/node-webkit
	sudo cp -a tagspaces/data/* $final_path
fi

# Files owned by www-data
sudo chown -R 755 $final_path
sudo chown -R www-data:www-data $final_path

#configure nginx settings
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add skipped_uris to SSOWat conf
sudo yunohost app setting $app is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
	sudo yunohost app setting $app skipped_uris -v "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf
